### PR TITLE
Create sudokuSolver.cpp

### PR DESCRIPTION
**Pull request by AJTEACH**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@AJTEACH 

**Thank you for contributing!**

- Please add yourself to CONTRIBUTORS.md

Don't forget to give a ⭐

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
Requested changes

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@AJTEACH 

Please add yourself to CONTRIBUTORS.md

**Comment by AJTEACH** [comment]
het @CODING-Enthusiast9857  added

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@AJTEACH 

**Thank you for contributing!**
Don't forget to give a ⭐

**Pull request merged**
