### PR TITLE
Added a cpp program to find frequency of characters in a word

### PR DESCRIPTION
**Pull request by TGFlame**
Hello! I am new to all of this so please let me know if I made any mistakes/missed something.
P.S how do I add people as reviewers?

### CODE REVIEW

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@TGFlame Thanks for contributing!

**Comment by CODING-Enthusiast9857** [comment]
To add people as reviewer - Navigate to Reviewers in the right sidebar. To request a review click again username

**Review by CODING-Enthusiast9857 — APPROVED** [review]
Don't forget to give a ⭐

**Review by CODING-Enthusiast9857 — APPROVED** [review]

**Comment by TGFlame** [comment]
Okay, Thanks!

**Pull request merged**
